name: Aether
main: xyz.jadonfowler.aether.Aether
version: 1.0
description: The Aether mod in a plugin.
author: http://jadonfowler.xyz
commands:
   aether:
      description: The main command for the Aether.